# Generated by Django 2.0.6 on 2021-08-05 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jailbreak',
            fields=[
                ('pk_Version', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('Version', models.CharField(max_length=50)),
                ('Desarollador', models.CharField(max_length=100, null=True)),
                ('descripcion', models.TextField(null=True)),
            ],
        ),
    ]
